version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pern_assessment
    container_name: postgres-nest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    networks:
      - backend
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/apps/client/node_modules
    depends_on:
      - api
    restart: always
    ports:
      - '3000:3000'

  api:
    container_name: api
    build:
      context: .
      dockerfile: api.dockerfile
    networks:
      - backend
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/apps/server/node_modules
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/pern_assessment
    ports:
      - '7001:7001'

networks:
  backend:
    driver: bridge